services:
    main-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
        networks:
            - app
        depends_on:
            - mysql
            - polygon
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'loz'
            MYSQL_USER: 'app'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - app
    polygon:
        build: ./polygon
        volumes:
            - './polygon:/usr/src/app'
        ports:
            - '8001:5000'
        networks:
            - app
networks:
    app:
        driver: bridge
volumes:
    mysql:
        driver: local
